### ISSUE TITLE
Loading hashtag automatically in the REPL?

### ISSUE THREAD

**Issue by Futurile** [sparkofreason/hashtag#3]
I'm a hobbyist and started messing with #hashp to visualise what's happening in functions. I'm trying out hashtag as it can show local variables. 

But, I'm struggling to automate having it in the REPL, and I'm not sure if it's a bug or it's my total lack of understanding of how data reader and macros work.

I've got a user.clj with the following: 

```
    ;; in my ns requirements
     [sparkofreason.hashtag.core :as ht :refer [defhashtag]]
     [puget.printer :as puget]
     [puget.color.ansi :as color]

    (defhashtag pp pprint)
  ```
When I start the REPL, it says #pp isn't there: 
```
user=> (take 20 (repeat #pp (+ 1 2 3)))
             java.lang.RuntimeException: No reader function for tag pp
clojure.lang.LispReader$ReaderException: java.lang.RuntimeException: No reader function for tag pp
```
If I run ``` (defhashtag pp pprint)``` then it runs fine. 

I can see in hashp that it loads a data_reader (https://github.com/weavejester/hashp/blob/master/src/data_readers.clj), and found some references to this on clojure.org. In the root of the project I added a data_readers.clj and added:

```
{pp user/pp*}
```

But that's not working. I found a note on https://clojuredocs.org/clojure.core/*data-readers* that "Reader tags without namespace qualifiers are reserved for Clojure" but I can't get it to work on any variation. 

Is there a way to automate adding the data reader?

**Comment by sparkofreason** [comment]
Make sure that `data_readers.clj` is in your classpath, i.e. in a directory specified either in `:paths` or `:extra-paths` in `deps.edn` (if you're using that). There's an "issue" with the order of how things are loaded by the REPL which ultimately means that `defhashtag` needs to be evaluated after the REPL has started.

Because of this and other similar funky issues, I kind of abandoned this project (and its generalization https://github.com/sparkofreason/hash-meta) because of headaches trying to get it to work across the spectrum of clj/cljs/repl/etc. I have a version hard-coded uses `tap>` which has proven very handy, but have dragged my feet in releasing it. Will try to get that together and deprecate these projects soon.

**Comment by Futurile** [comment]
Ah understood, thanks for the info. Pity that you've had to abandon it. Your 'feature' list looked very compelling having played with the other tools: 

* provide a tag if you have a log of debug
* handles threaded macro
* returns local variables
* provide timestamp
* additional framestacks
* configuration based debugging

**Comment by sparkofreason** [comment]
The `tap>`-based version has most of that, either included or easily implemented in the subscriber function. That's why I decided to deprecate this version. You get the same benefits, but easier to implement.
